# ==========================================
# MOFFAT BAY MARINA DATABASE
# ==========================================

db.host=localhost
db.port=3306
db.name=moffat_bay
db.user=root
db.password=

db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://marina-db:3306/moffat_bay?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=marina_app
db.password=greenteam